name: Validate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  home-assistant:
    name: Home Assistant validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "home-assistant/actions/hassfest@master"
